# Generated by Django 2.2 on 2020-04-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimgproject',
            name='img_inpaint',
            field=models.ImageField(blank=True, upload_to='main/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='mimgproject',
            name='img_mask',
            field=models.ImageField(blank=True, upload_to='main/%y/%m/%d/'),
        ),
    ]
