# Generated by Django 2.2 on 2020-04-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200402_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimgproject',
            name='ocr_data',
            field=models.TextField(blank=True),
        ),
    ]
