# Generated by Django 2.2 on 2020-04-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200402_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimgproject',
            name='img_temp',
            field=models.ImageField(blank=True, upload_to='main/%y/%m/%d/'),
        ),
    ]
