# Generated by Django 2.2 on 2020-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mimgproject_img_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mimgproject',
            old_name='img_temp',
            new_name='img_view',
        ),
        migrations.AddField(
            model_name='mimgproject',
            name='input_history',
            field=models.TextField(blank=True),
        ),
    ]
