# Generated by Django 2.2 on 2020-04-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200404_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muser',
        ),
    ]
