# Generated by Django 2.2 on 2020-04-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_projectform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectForm',
        ),
    ]
