# Generated by Django 2.2 on 2020-04-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectForm',
        ),
    ]
